import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { supabase } from "@/lib/supabase";

// GET: Fetch all chats for the current user
export async function GET() {
  try {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    // 1. Find the user's internal session ID
    const { data: member } = await supabase.from("members").select("id").eq("clerk_id", userId).single();
    const { data: session } = await supabase.from("sessions").select("id").eq("member_id", member?.id).single();

    if (!session) return NextResponse.json({ chats: [] }, { status: 200 });

    // 2. Fetch all non-deleted chats
    const { data: chats, error } = await supabase
      .from("chats")
      .select("id, url_id, description, timestamp")
      .eq("creator_id", session.id)
      .neq("is_deleted", true)
      .order("timestamp", { ascending: false });

    if (error) throw error;

    return NextResponse.json({ chats }, { status: 200 });
  } catch (error) {
    console.error("Error fetching chats:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}

// POST: Create a new chat
export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { id } = await req.json(); // The initialId generated by the frontend

    const { data: member } = await supabase.from("members").select("id").eq("clerk_id", userId).single();
    const { data: session } = await supabase.from("sessions").select("id").eq("member_id", member?.id).single();

    if (!session) return NextResponse.json({ error: "No active session" }, { status: 400 });

    const { data: newChat, error } = await supabase
      .from("chats")
      .insert({
        creator_id: session.id,
        id: id,
        timestamp: new Date().toISOString(),
        is_deleted: false,
        last_subchat_index: 0,
      })
      .select()
      .single();

    if (error) throw error;

    return NextResponse.json({ chat: newChat }, { status: 200 });
  } catch (error) {
    console.error("Error creating chat:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}