import { marked } from "marked";

// Marked configure karo
marked.setOptions({
    breaks: true,
    gfm: true,
});

/**
 * Markdown text ko HTML mein convert karta hai
 * Code blocks mein copy button IDs add karta hai
 */
export function renderMarkdown(text: string): string {
    let html = marked.parse(text) as string;

    // Code blocks mein wrapper + copy button add karo
    html = html.replace(
        /<pre><code( class="language-(\w+?)")?>([\s\S]*?)<\/code><\/pre>/g,
        (_match, _langClass, lang, code) => {
            const id = `cb-${Date.now().toString(36)}-${Math.random().toString(36).substring(2, 7)}`;
            const langLabel = lang || "code";
            return `<div class="code-wrap">
        <div class="code-header">
          <span><i class="fas fa-code" style="margin-right:6px;opacity:0.5"></i>${langLabel}</span>
          <button onclick="navigator.clipboard.writeText(document.getElementById('${id}')?.textContent||'').then(()=>{})" class="copy-btn">
            <i class="fas fa-copy"></i> Copy
          </button>
        </div>
        <pre><code id="${id}">${code}</code></pre>
      </div>`;
        }
    );

    return html;
}

/**
 * Chat ko Markdown file format mein export karta hai
 */
export function exportChatAsMarkdown(
    title: string,
    messages: { role: string; content: string }[]
): void {
    let md = `# ${title}\n\n`;
    md += `*Generated by PlanForge AI on ${new Date().toLocaleDateString()}*\n\n---\n\n`;

    for (const msg of messages) {
        if (msg.role === "user") {
            md += `## User\n${msg.content}\n\n`;
        } else {
            md += `## PlanForge AI\n${msg.content}\n\n`;
        }
    }

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/[^a-zA-Z0-9]/g, "_")}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}